project:
  name: CodeBuild-Demo
  regions:
  - us-east-1
tests:
  vpc-defaults:
    template: ./templates/EC2.yaml
    regions:
    - us-east-1  
    parameters:
      NameOfService: "TaskCat demo"
